sudo: required
services:
  - docker

before_install:
  - docker build -t mohamed/docker_aws_react_gmail_app -f Dockerfile.dev .

script:
  - docker run -e CI=true mohamed/docker_aws_react_gmail_app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker_aws_eact_gmail_firebase_app"
  env: "Dockerawseactgmailfirebaseapp-env-1"
  bucket_name: "elasticbeanstalk-eu-west-3-661517513609"
  bucket_path: "docker_aws_eact_gmail_firebase_app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

